"""The decisions a NEW tenant starts with - applied once, then the tenant's own.

There are two kinds of configuration in this product, and Frappe gives them the
same tool, which is the whole problem this module exists to solve:

    POLICY    what the customer may not change, because it is what they bought.
              Module access, plan gating. Re-applied on every deploy by
              module_access.sync_site(). Not here.

    BASELINE  decisions we made about how the product should behave, which a
              tenant STARTS with and may then change. Applied once, at
              provisioning. Never touched again. This module.

Frappe's answer to "ship default records with an app" is `fixtures`, and it
cannot do the second kind. sync_fixtures() runs on every `bench migrate` and
imports with `force=True` - no comparison, no merge. A customer changes a
setting, we deploy anything at all, and their change is silently reverted. That
is a default that cannot be overridden, which is not a default.

So this data lives in `baseline/`, NOT `fixtures/`, precisely so Frappe never
finds it. We apply it ourselves, once, and record that we did.

WHAT SHIPS IS A LIST OF DECISIONS, NOT A COPY OF A SITE.

That distinction was learned the expensive way. The first version of this module
captured whole doctypes from a tenant. Measured on a real one, that meant 582
Custom DocPerm rows, of which 264 were written by our own access control and
encoded THAT TENANT'S PLAN. Every new customer would have been born carrying
another customer's subscription, then fought with sync_site over it. The rest
were generated by Frappe HR and ERPNext during install - things a fresh site
creates for itself anyway.

None of the 582 was a decision anybody had made. So nothing sweeps here: each
list below names exactly what it ships, and a thing joins a list when somebody
decides it should be true for every customer.
"""

import json
import os

import frappe

STATE = "Alvoraa Access State"

# Records which release seeded a site. Bumping it does NOT re-seed anyone.
BASELINE_VERSION = "1"


# ── The decisions ────────────────────────────────────────────────────────────

# Doctypes whose PERMISSIONS are a product decision. Their Custom DocPerm rows
# are captured and shipped.
#
# Letter Head (2026-08-30): restricted to HR Manager and System Manager. An
# employee could read it through the Desk User role, which every system user
# holds automatically.
PERMISSION_DEFAULTS = [
    "Letter Head",
]

# Frappe HR's User Types carry `select_doctypes`, and saving a User Type
# regenerates select permissions from that list. So a doctype removed only in
# the Role Permissions Manager comes back - hrms.setup.update_select_perm_after_install
# runs after certain migrations and puts it there again.
#
# Expressed as a REMOVAL rather than a copy of the User Type record. Shipping the
# whole record would freeze one tenant's copy of a list Frappe HR maintains, and
# we would silently hold back their future additions. Subtracting leaves their
# list alone and takes out only what we decided against.
SELECT_REMOVALS = {
    "Employee Self Service": ["Letter Head"],
}

# Doctypes whose FIELD customisations are a product decision. Custom Field and
# Property Setter rows are shipped for these and no others.
#
# Empty on purpose. The product owner chose (2026-08-30) that custom fields are
# overridable defaults rather than enforced policy - so the mechanism is here -
# but nothing has been decided yet, and a fresh tenant already gets every custom
# field ERPNext and Frappe HR install for themselves. Add a doctype here only
# when OUR customisation of it should reach every customer.
CUSTOMISED_DOCTYPES = []

# Never shipped, whatever else changes, with the reason stated so nobody
# "helpfully" adds them back. These hold one organisation's DATA - shipping them
# would put one customer's staff, structure or logo into the next customer's site.
EXCLUDED = {
    "Company": "the customer's own company",
    "Employee": "real people",
    "Department": "one organisation's structure",
    "Branch": "one organisation's locations",
    "Letter Head": "carries a logo and address - the PERMISSIONS ship, the content does not",
    "Holiday List": "country and company specific",
    "User": "real accounts and credentials",
}


def _baseline_dir():
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "baseline")


PERM_FILE = "permissions.json"
SELECT_FILE = "select_removals.json"
FIELD_FILE = "field_customisations.json"


# ── Capture: a tenant site -> the repo ───────────────────────────────────────

def capture():
    """Write the decisions above out of THIS site and into the app.

    Run against a TENANT, never the control plane: the control plane is not
    shaped like a customer site, and sync_site refuses to run there for the same
    reason.

    The git diff this produces is the review gate, and it is the only one.
    Whatever is in it is what every future customer receives.
    """
    if frappe.conf.get("alvoraa_control_plane"):
        msg = ("Refusing to capture from the control plane. It is not a tenant, "
               "so its settings are not what a customer site looks like.")
        print(msg)
        return {"skipped": True, "reason": msg}

    from frappe.core.doctype.data_import.data_import import export_json

    out = _baseline_dir()
    os.makedirs(out, exist_ok=True)
    written = {}

    # Permissions, for the named doctypes only.
    wanted = [d for d in PERMISSION_DEFAULTS if d not in EXCLUDED or d == "Letter Head"]
    wanted = [d for d in wanted if frappe.db.exists("DocType", d)]
    if wanted:
        export_json("Custom DocPerm", os.path.join(out, PERM_FILE),
                    filters={"parent": ["in", wanted]})
        n = frappe.db.count("Custom DocPerm", {"parent": ["in", wanted]})
        written["permissions"] = {"doctypes": wanted, "rows": n}
        print(f"  captured permissions for {wanted} ({n} rows)")

    # Select removals are a decision, not an export - written straight out.
    with open(os.path.join(out, SELECT_FILE), "w", encoding="utf-8") as fh:
        json.dump(SELECT_REMOVALS, fh, indent=1)
    written["select_removals"] = SELECT_REMOVALS
    print(f"  wrote select removals: {SELECT_REMOVALS}")

    # Field customisations, for the named doctypes only.
    if CUSTOMISED_DOCTYPES:
        payload = {
            "Custom Field": frappe.get_all(
                "Custom Field", filters={"dt": ["in", CUSTOMISED_DOCTYPES]},
                fields=["*"], limit_page_length=0),
            "Property Setter": frappe.get_all(
                "Property Setter", filters={"doc_type": ["in", CUSTOMISED_DOCTYPES]},
                fields=["*"], limit_page_length=0),
        }
        with open(os.path.join(out, FIELD_FILE), "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=1, default=str)
        written["field_customisations"] = {k: len(v) for k, v in payload.items()}
        print(f"  captured field customisations for {CUSTOMISED_DOCTYPES}")

    return {"captured": written, "path": out}


# ── Apply: the repo -> a NEW tenant ──────────────────────────────────────────

def _already_applied():
    if not frappe.db.exists("DocType", STATE):
        return None
    return frappe.db.get_single_value(STATE, "baseline_applied")


def _apply_select_removals(removals):
    """Take our decisions out of each User Type's select list.

    Subtraction, so Frappe HR keeps ownership of everything else in that list.
    Saving the User Type is what regenerates the select permissions.
    """
    done = []
    for user_type, doctypes in (removals or {}).items():
        if not frappe.db.exists("User Type", user_type):
            continue
        doc = frappe.get_doc("User Type", user_type)
        keep = [r for r in (doc.get("select_doctypes") or [])
                if r.document_type not in doctypes]
        if len(keep) == len(doc.get("select_doctypes") or []):
            continue                    # nothing of ours was in there
        doc.set("select_doctypes", [])
        for r in keep:
            doc.append("select_doctypes", {"document_type": r.document_type})
        doc.flags.ignore_links = True
        doc.flags.ignore_permissions = True
        doc.save(ignore_permissions=True)
        done.append({user_type: doctypes})
    return done


def apply(force=False):
    """Seed this site from the captured decisions. Once.

    The guard is the point. Running twice would overwrite whatever the tenant
    changed in between - the exact failure that makes `fixtures` unusable here.
    `force` exists for deliberate support work on one site, and provisioning
    never passes it.
    """
    applied = _already_applied()
    if applied and not force:
        msg = (f"Baseline {applied} already applied to this site. Re-applying "
               f"would overwrite whatever the tenant has changed since.")
        print(msg)
        return {"skipped": True, "reason": msg, "applied": applied}

    d = _baseline_dir()
    if not os.path.isdir(d):
        return {"skipped": True, "reason": "no baseline captured yet"}

    from frappe.core.doctype.data_import.data_import import import_doc

    result = {"permissions": None, "select_removals": None, "failed": []}

    perm_path = os.path.join(d, PERM_FILE)
    if os.path.exists(perm_path):
        try:
            import_doc(perm_path)
            result["permissions"] = PERMISSION_DEFAULTS
        except Exception:
            result["failed"].append(PERM_FILE)
            frappe.log_error(title="baseline: permissions failed",
                             message=frappe.get_traceback())

    sel_path = os.path.join(d, SELECT_FILE)
    if os.path.exists(sel_path):
        try:
            with open(sel_path, encoding="utf-8") as fh:
                result["select_removals"] = _apply_select_removals(json.load(fh))
        except Exception:
            result["failed"].append(SELECT_FILE)
            frappe.log_error(title="baseline: select removals failed",
                             message=frappe.get_traceback())

    field_path = os.path.join(d, FIELD_FILE)
    if os.path.exists(field_path):
        try:
            import_doc(field_path)
        except Exception:
            result["failed"].append(FIELD_FILE)
            frappe.log_error(title="baseline: field customisations failed",
                             message=frappe.get_traceback())

    if frappe.db.exists("DocType", STATE):
        doc = frappe.get_single(STATE)
        doc.baseline_applied = BASELINE_VERSION
        doc.flags.ignore_permissions = True
        doc.save(ignore_permissions=True)
    frappe.db.commit()

    result["version"] = BASELINE_VERSION
    return result
